export const THEMES = [
  {
    id: "midnight-aurora",
    name: "Midnight Aurora",
    bg: "#080B14",
    surface: "#121827",
    accent: "#8B5CF6",
    text: "#F8FAFC",
  },
  {
    id: "graphite-lime",
    name: "Graphite Lime",
    bg: "#0B0D0C",
    surface: "#171B18",
    accent: "#B7F34A",
    text: "#F4F7F2",
  },
  {
    id: "ocean-glass",
    name: "Ocean Glass",
    bg: "#06141F",
    surface: "#102B3A",
    accent: "#22D3EE",
    text: "#E6F9FF",
  },
  {
    id: "royal-noir",
    name: "Royal Noir",
    bg: "#100817",
    surface: "#24132F",
    accent: "#C084FC",
    text: "#FAF5FF",
  },
  {
    id: "ember-studio",
    name: "Ember Studio",
    bg: "#160B08",
    surface: "#2A1711",
    accent: "#FB923C",
    text: "#FFF7ED",
  },
  {
    id: "arctic-minimal",
    name: "Arctic Minimal",
    bg: "#EAF0F6",
    surface: "#FFFFFF",
    accent: "#2563EB",
    text: "#101828",
  },
];